### ISSUE TITLE
Can't Resolve 'react'

### ISSUE THREAD

**Issue by williamluke4** [michal-wrzosek/react-component-lib#1]
Hey @michal-wrzosek, I came from your medium article and have been struggling to get this working. Do you have any idea what is going on here?
```
Module not found: Can't resolve 'react' in 'D:\Documents\Projects\react-component-lib\dist'
```

**Comment by williamluke4** [comment]
Ok, I have worked it out! 
When using `npm link` you must also `npm link` react and react-dom from the project you are linking the library to. As if you try to install react as a devDependence in the library you will run in to the following issue. 
```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. 
This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

**Comment by michal-wrzosek** [comment]
Hi @williamluke4 !
Thank you for your message :) I'll check this out and get back to you.

**Comment by michal-wrzosek** [comment]
Hi @williamluke4
I would really like to help you but I can't fully understand your issue. The idea of this repo was that you don't have to use npm link.

**Comment by williamluke4** [comment]
@michal-wrzosek Sorry I didn't explain this very well. My second comment was actually how I solved it. It was to do with React Hooks being very picky with using sperate instances of react

**Comment by michal-wrzosek** [comment]
Ok, that's interesting. I'll check how hooks are working with this repo. Maybe I can improve something. Thank you for your message :)

**Comment by williamluke4** [comment]
#### An attempt to explain a bit better
I was using `npm link` in my component library then using `npm link my-component-lib' in my frontend project. As i had added react to the devDependecies so I could work on the documentation of the components, It lead to there being a conflict between the react  in my-components-lib and my main projects react.
